global using SunamoGitConfig.Data;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System;
global using SunamoGitConfig._sunamo;
global using SunamoGitConfig.Enums;
global using SunamoGitConfig;
global using SunamoGitConfig.Consts;
