name: Build SunamoGitConfig

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoGitConfig
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGitConfig/SunamoGitConfig.csproj

    - name: Build
      run: dotnet build SunamoGitConfig/SunamoGitConfig.csproj --configuration Release --no-restore

  test:
    name: Test SunamoGitConfig.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoGitConfig.Tests/SunamoGitConfig.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoGitConfig.Tests/SunamoGitConfig.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoGitConfig.Tests/SunamoGitConfig.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
